### ISSUE TITLE
진행하는데 어려움이 있으신가요?

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-spring-1-mikekang47#10]
직접 해보면서 할 줄 모른다는 피드백을 얻고, 그 피드백을 통해서 공부하고 직접 만들어서 내가 할 수 있다는 피드백을 얻어보세요.
공부를 할 때 내가 무엇을 할 수 있게 되는지 집중해보시면 학습의 방향을 설정하는데 도움이 되실거에요

**Comment by mikekang47** [comment]
오늘에서야 드디어 해결했습니다! 감사합니다 윤석님
사실 학교과제가 쏟아지고 개인적으로 일도 많이 생겨서 어떻게 해야할지 모르고 있었는데 
끙끙앓던 문제가 해결되어서 순조롭게 진행할 수 있을 것 같습니다!

**Comment by hannut91** [comment]
문제가 해결되어 이슈를 종료합니다 🥰
